# --- CONFIGURACI\u00D3N B\u00C1SICA ---
spring.application.name=backend
server.port=8088

# --- DATOS DE CONEXI\u00D3N ---
# He puesto el puerto 3308 que es el que mapeaste en tu Docker
spring.datasource.url=jdbc:mysql://localhost:3308/dam_project_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=dam_user
spring.datasource.password=dam_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / HIBERNATE ---
# 'validate' para que respete tus scripts de la carpeta init y no cambie nada
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true